version: '3.4'

services:
  testdockercompose:
    image: ${DOCKER_REGISTRY-}testdockercompose
    build:
      context: .
      dockerfile: testDockerCompose/Dockerfile
    ports:
     - "5000:5000"
     - "5001:5001"
